theme: jekyll-theme-midnight

title: Diabetes Data Diving Final Write-up
authors:
  nilai:
    name: Nilai Vemula
    display_name: Nilai
    email: nilai.r.vemula@vanderbilt.edu
    web: http://nilaivemula.github.io/
    github: NilaiVemula
  anvitha:
    name: Anvitha Kosuraju
    display_name: Anvitha
  sithara:
    name: Sithara Samudrala
    display_name: Sithara
